// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQjbriWJqrOkW4EsLQn6b4ydVkYM9M0i8',
    appId: '1:327568063541:web:ac3930369ed549d651857c',
    messagingSenderId: '327568063541',
    projectId: 'my-finance-app-bd78f',
    authDomain: 'my-finance-app-bd78f.firebaseapp.com',
    storageBucket: 'my-finance-app-bd78f.firebasestorage.app',
    measurementId: 'G-F6RRJX20NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0I6yry39dCI8WUAdg2lRwqv_VlhPHoPo',
    appId: '1:327568063541:android:d7ffa7c81f6c06d251857c',
    messagingSenderId: '327568063541',
    projectId: 'my-finance-app-bd78f',
    storageBucket: 'my-finance-app-bd78f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxj3Gl9OEizF-auUbh5ohuSAHHDXQJb0o',
    appId: '1:327568063541:ios:fd20efd7cb12b00751857c',
    messagingSenderId: '327568063541',
    projectId: 'my-finance-app-bd78f',
    storageBucket: 'my-finance-app-bd78f.firebasestorage.app',
    iosBundleId: 'com.example.myfinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxj3Gl9OEizF-auUbh5ohuSAHHDXQJb0o',
    appId: '1:327568063541:ios:fd20efd7cb12b00751857c',
    messagingSenderId: '327568063541',
    projectId: 'my-finance-app-bd78f',
    storageBucket: 'my-finance-app-bd78f.firebasestorage.app',
    iosBundleId: 'com.example.myfinance',
  );
}
